# Generated by Django 3.0.8 on 2020-07-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrymodel',
            name='entry_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
